repo = {
    "GitHub":[
        {
            "name":"Far Manager",
            "version_link":"/FarGroup/FarManager",
            "path_to_exe":"C:\\PortableApps\\Far\\Far.exe",
            "download_link":"https://github.com/FarGroup/FarManager/releases/latest"
        },
        {
            "name":"OBS Studio",
            "version_link":"/obsproject/obs-studio",
            "path_to_exe":"C:\\PortableApps\\OBSStudio\\bin\\64bit\\obs64.exe",
            "download_link":"https://github.com/obsproject/obs-studio/releases/latest"
        },
        {
            "name":"Rufus",
            "version_link":"/pbatard/rufus",
            "path_to_exe":"C:\\PortableApps\\Rufus\\rufus.exe",
            "download_link":"https://github.com/pbatard/rufus/releases/latest"
        },
        {
            "name":"VSCode",
            "version_link":"/Microsoft/vscode",
            "path_to_exe":"C:\\PortableApps\\VSCode\\Code.exe",
            "download_link":"https://code.visualstudio.com/#alt-downloads"
        },
        {
            "name":"Telegram",
            "version_link":"/telegramdesktop/tdesktop",
            "path_to_exe":"K:\\Telegram\\Telegram.exe",
            "download_link":"https://github.com/telegramdesktop/tdesktop/releases/latest"
        }
    ],
    "PortableApps":[
        {
            "name":"PDF-XChange Editor",
            "version_link":"https://portableapps.com/apps/office/pdf-xchange-editor-portable",
            "path_to_exe":"C:\\PortableApps\\PDFXChangeEditor\\PDFXEdit.exe",
            "download_link":"https://www.tracker-software.com/product/pdf-xchange-editor"
        },
        {
            "name":"Free Download Manager",
            "version_link":"https://portableapps.com/apps/internet/free-download-manager-portable",
            "path_to_exe":"C:\\PortableApps\\FreeDownloadManagerPortable\\App\\FreeDownloadManager\\fdm.exe",
            "download_link":"https://portableapps.com/apps/internet/free-download-manager-portable"
        },
        {
            "name":"FastStone Image Viewer",
            "version_link":"https://portableapps.com/apps/graphics_pictures/faststone-image-viewer-portable",
            "path_to_exe":"C:\\PortableApps\\FSViewer\\FSViewer.exe",
            "download_link":"https://www.faststone.org/FSIVDownload.htm"
        },
        {
            "name":"GIMP",
            "version_link":"https://portableapps.com/apps/graphics_pictures/gimp_portable",
            "path_to_exe":"C:\\PortableApps\\GIMPPortable\\App\\gimp\\bin\\gimp-2.10.exe",
            "download_link":"https://portableapps.com/apps/graphics_pictures/gimp_portable"
        },
        {
            "name":"Notepad++",
            "version_link":"https://portableapps.com/apps/development/notepadpp_portable",
            "path_to_exe":"C:\\PortableApps\\Notepad++Portable\\App\\Notepad++64\\notepad++.exe",
            "download_link":"https://portableapps.com/apps/development/notepadpp_portable"
        },
        {
            "name":"PotPlayer",
            "version_link":"https://portableapps.com/apps/music_video/potplayer-portable",
            "path_to_exe":"C:\\PortableApps\\PotPlayerPortable\\App\\PotPlayer\\PotPlayer.dll",
            "download_link":"https://portableapps.com/apps/music_video/potplayer-portable"
        },
        {
            "name":"Shotcut",
            "version_link":"https://portableapps.com/apps/music_video/shotcut-portable",
            "path_to_exe":"C:\\PortableApps\\ShotcutPortable\\App\\Shotcut64\\shotcut.exe",
            "download_link":"https://portableapps.com/apps/music_video/shotcut-portable"
        },
        {
            "name":"LibreOffice",
            "version_link":"https://portableapps.com/apps/office/libreoffice_portable",
            "path_to_exe":"C:\\PortableApps\\LibreOfficePortable\\App\\libreoffice\\program\\soffice.exe",
            "download_link":"https://portableapps.com/apps/office/libreoffice_portable"
        },
        {
            "name":"Sumatra PDF",
            "version_link":"https://portableapps.com/apps/office/sumatra_pdf_portable",
            "path_to_exe":"C:\\PortableApps\\SumatraPDF\\SumatraPDF.exe",
            "download_link":"https://www.sumatrapdfreader.org/download-free-pdf-viewer"
        },
        {
            "name":"Thunderbird",
            "version_link":"https://portableapps.com/apps/internet/thunderbird_portable",
            "path_to_exe":"K:\\ThunderbirdPortable\\App\\Thunderbird64\\thunderbird.exe",
            "download_link":"https://portableapps.com/apps/internet/thunderbird_portable"
        },
        {
            "name":"WinCDEmu",
            "version_link":"https://portableapps.com/apps/utilities/wincdemu-portable",
            "path_to_exe":"C:\\PortableApps\\WinCDEmuPortable\\App\\WinCDEmu\\PortableWinCDEmu-x.x.exe",
            "download_link":"https://portableapps.com/apps/utilities/wincdemu-portable"
        },
        {
            "name":"qBittorrent",
            "version_link":"https://portableapps.com/apps/internet/qbittorrent_portable",
            "path_to_exe":"C:\\PortableApps\\qBittorrentPortable\\App\\qBittorrent\\qbittorrent.exe",
            "download_link":"https://portableapps.com/apps/internet/qbittorrent_portable"
        },
        {
            "name":"Firefox",
            "version_link":"https://portableapps.com/apps/internet/firefox_portable",
            "path_to_exe":"K:\\FirefoxPortable\\App\\Firefox\\firefox.exe",
            "download_link":"https://portableapps.com/apps/internet/firefox_portable"
        }
    ],
    "Techspot":[
        {
            "name":"Autoruns",
            "version_link":"https://www.techspot.com/downloads/2879-autoruns.html",
            "path_to_exe":"C:\\PortableApps\\Autoruns\\Autoruns64.exe",
            "download_link":"https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns"
        },
        {
            "name":"foobar200",
            "version_link":"https://www.techspot.com/downloads/2258-foobar.html",
            "path_to_exe":"C:\\PortableApps\\foobar2000\\foobar2000.exe",
            "download_link":"https://www.foobar2000.org/download"
        },
        {
            "name":"MSI Afterburner",
            "version_link":"https://www.techspot.com/downloads/4895-msi-afterburner.html",
            "path_to_exe":"C:\\PortableApps\\MSI Afterburner\\MSIAfterburner.exe",
            "download_link":"https://www.guru3d.com/files-details/msi-afterburner-beta-download.html"
        },
        {
            "name":"Process Explorer",
            "version_link":"https://www.techspot.com/downloads/362-process-explorer.html",
            "path_to_exe":"C:\\PortableApps\\ProcessExplorer\\procexp64.exe",
            "download_link":"https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer"
        },
        {
            "name":"REAPER",
            "version_link":"https://www.techspot.com/downloads/2642-reaper.html",
            "path_to_exe":"C:\\PortableApps\\REAPER\\reaper.exe",
            "download_link":"https://www.reaper.fm/download.php"
        },
        {
            "name":"WinRAR",
            "version_link":"https://www.techspot.com/downloads/67-winrar.html",
            "path_to_exe":"C:\\PortableApps\\WinRAR\\WinRAR.exe",
            "download_link":"https://www.win-rar.com/start.html?&L=0"
        },
        {
            "name":"WizTree",
            "version_link":"https://www.techspot.com/downloads/7470-wiztree.html",
            "path_to_exe":"C:\\PortableApps\\WizTree\\WizTree64.exe",
            "download_link":"https://www.diskanalyzer.com/download"
        }
    ]
}